### ISSUE TITLE
Update the Install guide

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/web-map-doc#54] opened 2021-09-27 15:38 UTC
Since @erictheise updated our npm registry, I believe we're able to install the custom element via npm install.  So, we should update the [Installation Guide](https://maps4html.org/web-map-doc/docs/installation) to reflect that.

**Comment by Malvoz** [comment] 2022-10-25 16:20
Duplicate of #35

**Closed by Malvoz** 2022-10-25 16:20 UTC
